import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <ul>
            <li>
              <Link href="/">
                <span className="font-bold text-lg">Home</span>
              </Link>
              /
              <Link href="/counter">
                <span className="font-bold text-lg">Counter</span>
              </Link>
              /
              <Link href="/movie-csr">
                <span className="font-bold text-lg">Movie-CSR</span>
              </Link>
              /
              <Link href="/movie-ssr">
                <span className="font-bold text-lg">Movie-SSR</span>
              </Link>
              /
              <Link href="/movie-csr-swr">
                <span className="font-bold text-lg">Movie-CSR-SWR</span>
              </Link>
              /
              <Link href="/movie-ssr-swr">
                <span className="font-bold text-lg">Movie-SSR-SWR</span>
              </Link>
              /
              <Link href="/todo">
                <span className="font-bold text-lg">Todo</span>
              </Link>
              /
              <Link href="/news">
                <span className="font-bold text-lg">News</span>
              </Link>
            </li>
          </ul>
        </header>

        {/* Page.tsx: 모든 하위 컴포넌트가 여기에 렌더링됨 */}
        <main>{children}</main>

        <footer>Footer</footer>
      </body>
    </html>
  )
}
